Libre2 Documentation
tzachi-dar/LibreAllHouse pull request #13
Opened 2021-10-05 11:57 UTC by jk1993

2021-10-05 20:42 UTC, tzachi-dar requested changes

2021-10-05 20:42 UTC, tzachi-dar commented on LIBRE2.md
> +3. Edit the config.cfg file to unter mongodb parameters (optional). (for example db_uri = mongodb+srv://userj:passi@cluster-b6k1n0tj.bg18m.mongodb.net/heroku_b6k1n0tj)
Due to the need for a shared key, libre2 does not work with mongodb. So, remove section 3.

2021-10-05 20:42 UTC, tzachi-dar commented on LIBRE2.md
> +    sudo apt-get install -y git
Move this part to step 3

2021-10-05 20:42 UTC, tzachi-dar commented on LIBRE2.md
> +
Remove mongodb from this step as well.

2021-10-05 20:42 UTC, tzachi-dar commented on LIBRE2.md
> +## Step 7 - Configure the pi to also upload data to a mongodb (optional).
Remove step 7

2021-10-05 20:42 UTC, tzachi-dar commented on LIBRE2.md
> +## Step 8 - Configure a phone as receiver (optional)
Remove step 8, it does not work for libre2

2021-10-05 20:56 UTC, jk1993 commented
I have made the requested changes. Let me know if I've missed anything. Thanks

2021-10-06 19:57 UTC, merged

2021-10-06 19:57 UTC, tzachi-dar commented
Thanks for your help!